name: Unity Build & Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Unity Project
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        targetPlatform: [StandaloneWindows64, StandaloneOSX]

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Unity (Replace version with your actual Unity version)
      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.30f1
          targetPlatform: ${{ matrix.targetPlatform }}

      # 3️⃣ Activate Unity License (required for CI/CD)
      - name: Activate Unity License
        uses: game-ci/unity-activate@v4
        with:
          unityVersion: 6000.0.30f1
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}
          unitySerial: ${{ secrets.UNITY_SERIAL }}

      # 4️⃣ Build the Unity project
      - name: Build for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # 5️⃣ Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UnityBuild-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
